### ISSUE TITLE
Backend segfault when importing data with v1.1.6

### ISSUE THREAD

**Issue by PromyLOPh** [garlik/4store#135]
Trying to import data (two files, each 1 GB triples in Turtle format) with 4s-import, the 4s-backend segfaults with the current git HEAD and v1.1.6. v1.1.5 works, but I can’t narrow it down to a single commit with `git bisect`, because builds in between fail with `../common/uuid.h:18:19: fatal error: uuid.h: No such file or directory`. If there’s a workaround for that I’d be happy to apply it and do another bisect.

Valgrind report: https://gist.github.com/PromyLOPh/f006f27ef728f55ed616
gdb backtrace: https://gist.github.com/PromyLOPh/fd8383342d579c22177c

**Comment by swh** [comment]
89ec910c8460bd171825ed44e402983251466a0b looks like it makes a lot of changes re. uuid, and was added between v1.1.5 and v1.1.6,  so you could try applying that?

**Comment by PromyLOPh** [comment]
Strange, the uuid issue disappeared after a `make distclean`. Anyway,
`git bisect` says `af86d87414dfd70312222d7e6569f431cda106fb is the first
bad commit`. So I reverted that commit and 4s-import works again.

**Comment by swh** [comment]
Excellent, thanks.

What OS is this on?

**Comment by PromyLOPh** [comment]
It’s Gentoo Linux. Here’s the relevant output of ./configure as for libraries:

Configuration status:
   Cluster support available through 4s-boss
   Install Avahi (-glib and -client) to get mDNS support on Linux
   Using Linux-style libuuid
   Using Raptor version 2.0.9
   Using Rasqal version 0.9.29

glib version is 2.44.1. Anything else you need?

**Comment by swh** [comment]
That's fine - I was just wondering why this problem hasn't affected more people, but there's nothing really special about Gentoo - as far as I know.

I'm not sure if we should revert that patch from HEAD or not - it supposedly adds POSIX correctness, but I suspect it introduces a bug.

**Comment by PromyLOPh** [comment]
One thing I noticed about the patch: `header` is now a pointer, but
`sizeof(header)` is unchanged. The backend still crashes with
the following patch applied unfortunately
https://gist.github.com/anonymous/5a20ecccd76ce129f28b
